steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/submission-api', '.']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/submission-api']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'submission-api'
      - '--image'
      - 'gcr.io/$PROJECT_ID/submission-api'
      - '--platform'
      - 'managed'
      - '--region'
      - 'australia-southeast2'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'INSTANCE_CONNECTION_NAME=dcs-concept-submission-records:australia-southeast2:pj-test-db,NODE_ENV=production'
      - '--add-cloudsql-instances'
      - 'dcs-concept-submission-records:australia-southeast2:dcs-concept-submission-records'

images:
  - 'gcr.io/$PROJECT_ID/submission-api'